### ISSUE TITLE
Need a class created from an existing id

### ISSUE THREAD

**Issue by kristen-abell** [mental-health-america/mha#31]
@bwaye3 We are using the #blue-accordian id multiple times on a page when we should only be using ids once on any given page. I need this to be a class instead. Can you create a .blue-accordion class for me that I can apply anywhere we're currently using the #blue-accordian id with the same attributes? I will then go into the site and trade those out anywhere I find the #blue-accordian id. Thanks!

**Comment by kristen-abell** [comment]
> We are using the #blue-accordian id multiple times on a page when we should only be using ids once on any given page. I need this to be a class instead. Can you create a .blue-accordion class for me that I can apply anywhere we're currently using the #blue-accordian id with the same attributes? I will then go into the site and trade those out anywhere I find the #blue-accordian id. Thanks!

Actually - one edit on this - could we possibly make the text within the accordion open under it instead of to the side? Currently, the way it opens, the heading moves to the left, and the text inside opens to the right, which is fine on desktop, but on mobile is super squashed.

**Comment by bwaye3** [comment]
Closing and create new issue for text
